services:
  dashboard:
    build: .
    command: streamlit run dashboard/app.py --server.address=0.0.0.0 --server.port=8501
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8501:8501"

  api:
    build: .
    command: uvicorn rfm_pipeline.api.main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
